# Generated by Django 6.1.1 on 2026-09-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_add_source_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentitem",
            name="revision",
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="sourcestate",
            name="revision",
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
