# Generated by Django 6.1.1 on 2026-09-23 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_contentitem_revision_sourcestate_revision"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentitem",
            options={"ordering": ["-created_at", "title", "id"]},
        ),
    ]
